# Generated by Django 3.2.9 on 2021-11-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
