# Generated by Django 3.2.9 on 2021-11-21 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_genre_ids_movie_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genre_ids',
        ),
    ]
