# Generated by Django 3.2.9 on 2021-11-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rank_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Director',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='actor',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
