# Generated by Django 3.2.9 on 2021-11-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_actor_movie_actors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.JSONField(null=True),
        ),
    ]
