# Generated by Django 3.2.9 on 2021-11-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20211122_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Director',
            new_name='director',
        ),
    ]
