# Generated by Django 3.2.9 on 2021-11-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_article_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='username',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
