# Generated by Django 3.2.9 on 2021-11-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_article_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='like_users',
        ),
    ]
